name: wget
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "URL"
      Name:
        description: "Name"
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Wget
        run: |
          touch info.txt
          echo "Wget of mi20210630 developed" >> info.txt
          cd ${{ github.workspace }}
          mkdir files && cd files
          curl -O ${{ github.event.inputs.NAME }} -L ${{ github.event.inputs.URL }}
          
      - name: Upload to Release‌‌...
        uses: ncipollo/release-action@v1.8.0
        with:
          artifacts: "${{ github.workspace }}/files/*"
          tag: "${{ github.event.inputs.NAME }}_${{ env.BUILD_TIME }}"
          bodyFile: "./info.txt"
          token: ${{ secrets.PAT }}
